Readme update and Feedback section
IgniteUI/app-builder pull request #12
Opened 2022-05-11 14:54 UTC by zdrawku

2022-05-12 08:05 UTC, radomirchev requested changes
Add a field for reporting a bug. Do we have templates ready for feature request, bug and question?

2022-06-09 09:15 UTC, kdinev commented
@zdrawku Please update with the change requested!

2022-06-10 12:57 UTC, zdrawku commented
@radomirchev templates will be added next sprint, I need to sync with George about them.

2022-06-14 07:20 UTC, hanastasov approved these changes

2022-06-14 07:51 UTC, kdinev approved these changes

2022-06-14 07:52 UTC, merged